### ISSUE TITLE
why does not work dup tnt (quarry)

### ISSUE THREAD

**Issue by X1miya** [foss-mc/Patina#19]
When I wanted to make a career at your core, it didn't work. Is it so necessary? if so, how is it possible to fix it is very uncomfortable.

**Comment by toinouH** [comment]
Hello, thank you for reporting and as our upstream we have a very similar policy about exploits/bugs etc. I invite you to read the issue to fix your problem but it's unsupported :)
https://github.com/PaperMC/Paper/issues/3854 
I'm going to close this as "won't fix" as it's somehow already fixed by turning on an option and also because we won't turn this behaviour on by default.
